// The three model parsers, against bytes rather than against a mock.
//
// Every fixture here is built in the test - a real binary STL laid out to the
// byte, a real GLB with its two chunks and its four-byte padding - because the
// whole point of writing these parsers by hand was to avoid a dependency, and
// checking them against a fixture generated by the same code would check
// nothing.

import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  parseSTL, parseOBJ, parseGLB, parseMesh, meshKind, MeshError, MAX_TRIANGLES,
} from '../web/assets/js/import/mesh.js';

// A unit triangle in the z = 0 plane, wound anticlockwise so its normal is +z.
const TRI = {
  a: [0, 0, 0], b: [1, 0, 0], c: [0, 1, 0],
};

const near = (a, b, msg) => assert.ok(Math.abs(a - b) < 1e-5, `${msg}: ${a} vs ${b}`);

// ---------------------------------------------------------------------------
// STL
// ---------------------------------------------------------------------------

function binarySTL(triangles, header = 'a header') {
  const buf = new ArrayBuffer(84 + triangles.length * 50);
  const view = new DataView(buf);
  new Uint8Array(buf).set(new TextEncoder().encode(header.slice(0, 80)), 0);
  view.setUint32(80, triangles.length, true);
  triangles.forEach((t, i) => {
    const at = 84 + i * 50;
    const n = t.normal || [0, 0, 0];
    view.setFloat32(at, n[0], true);
    view.setFloat32(at + 4, n[1], true);
    view.setFloat32(at + 8, n[2], true);
    [t.a, t.b, t.c].forEach((v, k) => {
      view.setFloat32(at + 12 + k * 12, v[0], true);
      view.setFloat32(at + 16 + k * 12, v[1], true);
      view.setFloat32(at + 20 + k * 12, v[2], true);
    });
  });
  return buf;
}

test('a binary STL reads its triangles and its bounds', () => {
  const m = parseSTL(binarySTL([{ ...TRI, normal: [0, 0, 1] }]));
  assert.equal(m.count, 3);
  assert.deepEqual([...m.positions], [0, 0, 0, 1, 0, 0, 0, 1, 0]);
  assert.deepEqual(m.bounds.min, [0, 0, 0]);
  assert.deepEqual(m.bounds.max, [1, 1, 0]);
});

test('a binary STL whose header says "solid" is still binary', () => {
  // The bug this exists for: sniffing the leading word sends these files down
  // the ASCII path, where they parse as empty. The length arithmetic does not
  // care what the header says.
  const m = parseSTL(binarySTL([{ ...TRI, normal: [0, 0, 1] }], 'solid exported by something'));
  assert.equal(m.count, 3);
});

test('a facet with no normal gets the one its winding implies', () => {
  const m = parseSTL(binarySTL([{ ...TRI, normal: [0, 0, 0] }]));
  near(m.normals[0], 0, 'nx');
  near(m.normals[1], 0, 'ny');
  near(m.normals[2], 1, 'nz');
});

test('normals come out unit length whatever the file said', () => {
  const m = parseSTL(binarySTL([{ ...TRI, normal: [0, 0, 17] }]));
  near(Math.hypot(m.normals[0], m.normals[1], m.normals[2]), 1, 'length');
});

test('an ASCII STL reads the same triangle', () => {
  const text = `solid thing
  facet normal 0 0 1
    outer loop
      vertex 0 0 0
      vertex 1 0 0
      vertex 0 1 0
    endloop
  endfacet
endsolid thing`;
  const m = parseSTL(new TextEncoder().encode(text).buffer);
  assert.equal(m.count, 3);
  assert.deepEqual([...m.positions], [0, 0, 0, 1, 0, 0, 0, 1, 0]);
});

test('an ASCII STL survives exponents and negative numbers', () => {
  const text = `solid s
facet normal 0 0 1
outer loop
vertex -1.5e2 0 0
vertex 1 -2.25 0
vertex 0 1 3E-2
endloop
endfacet
endsolid s`;
  const m = parseSTL(new TextEncoder().encode(text).buffer);
  near(m.positions[0], -150, 'x');
  near(m.positions[4], -2.25, 'y');
  near(m.positions[8], 0.03, 'z');
});

test('an STL with nothing in it is an error, not an empty mesh', () => {
  assert.throws(() => parseSTL(new TextEncoder().encode('solid s\nendsolid s').buffer), MeshError);
});

test('a binary STL that lies about its triangle count is read as ASCII', () => {
  // 84 + 50n is the whole test for binary, so a header claiming a count the
  // length does not support must not be trusted to allocate against.
  const buf = new ArrayBuffer(200);
  new DataView(buf).setUint32(80, 4_000_000_000, true);
  assert.throws(() => parseSTL(buf), MeshError);
});

// ---------------------------------------------------------------------------
// OBJ
// ---------------------------------------------------------------------------

test('an OBJ reads faces and one-based indices', () => {
  const m = parseOBJ('v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 3\n');
  assert.equal(m.count, 3);
  assert.deepEqual([...m.positions], [0, 0, 0, 1, 0, 0, 0, 1, 0]);
});

test('an OBJ quad is fanned into two triangles', () => {
  const m = parseOBJ('v 0 0 0\nv 1 0 0\nv 1 1 0\nv 0 1 0\nf 1 2 3 4\n');
  assert.equal(m.count, 6);
});

test('negative OBJ indices count back from what has been read', () => {
  const m = parseOBJ('v 0 0 0\nv 1 0 0\nv 0 1 0\nf -3 -2 -1\n');
  assert.deepEqual([...m.positions], [0, 0, 0, 1, 0, 0, 0, 1, 0]);
});

test('an OBJ face may name normals, or leave them to be computed', () => {
  const given = parseOBJ('v 0 0 0\nv 1 0 0\nv 0 1 0\nvn 0 1 0\nf 1//1 2//1 3//1\n');
  near(given.normals[1], 1, 'the file said +y');
  const derived = parseOBJ('v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 3\n');
  near(derived.normals[2], 1, 'the winding says +z');
});

test('an OBJ ignores what it cannot draw rather than failing on it', () => {
  const m = parseOBJ([
    '# a comment', 'mtllib thing.mtl', 'o Object', 'g group', 's 1',
    'usemtl red', 'vt 0.5 0.5',
    'v 0 0 0', 'v 1 0 0', 'v 0 1 0', 'f 1/1 2/1 3/1', '',
  ].join('\n'));
  assert.equal(m.count, 3);
});

test('an OBJ with no faces is an error', () => {
  assert.throws(() => parseOBJ('v 0 0 0\nv 1 0 0\n'), MeshError);
});

// ---------------------------------------------------------------------------
// GLB
// ---------------------------------------------------------------------------

/** A real container: header, JSON chunk, BIN chunk, both padded to four. */
function glb(json, bin) {
  const enc = new TextEncoder();
  const pad = (bytes, filler) => {
    const need = (4 - (bytes.length % 4)) % 4;
    if (!need) return bytes;
    const out = new Uint8Array(bytes.length + need);
    out.set(bytes);
    out.fill(filler, bytes.length);
    return out;
  };
  const j = pad(enc.encode(JSON.stringify(json)), 0x20);   // spaces
  const b = pad(bin, 0);
  const total = 12 + 8 + j.length + 8 + b.length;
  const buf = new ArrayBuffer(total);
  const v = new DataView(buf);
  const u = new Uint8Array(buf);
  v.setUint32(0, 0x46546c67, true);
  v.setUint32(4, 2, true);
  v.setUint32(8, total, true);
  v.setUint32(12, j.length, true);
  v.setUint32(16, 0x4e4f534a, true);
  u.set(j, 20);
  const at = 20 + j.length;
  v.setUint32(at, b.length, true);
  v.setUint32(at + 4, 0x004e4942, true);
  u.set(b, at + 8);
  return buf;
}

/** One triangle: three VEC3 positions, then three unsigned-short indices. */
function triangleGLB(extra = {}) {
  const positions = new Float32Array([0, 0, 0, 1, 0, 0, 0, 1, 0]);
  const indices = new Uint16Array([0, 1, 2]);
  const bin = new Uint8Array(positions.byteLength + 8);   // 8 = indices, padded
  bin.set(new Uint8Array(positions.buffer), 0);
  bin.set(new Uint8Array(indices.buffer), positions.byteLength);
  return glb({
    asset: { version: '2.0' },
    scene: 0,
    scenes: [{ nodes: [0] }],
    nodes: [{ mesh: 0, ...extra }],
    meshes: [{ primitives: [{ attributes: { POSITION: 0 }, indices: 1 }] }],
    accessors: [
      { bufferView: 0, componentType: 5126, count: 3, type: 'VEC3' },
      { bufferView: 1, componentType: 5123, count: 3, type: 'SCALAR' },
    ],
    bufferViews: [
      { buffer: 0, byteOffset: 0, byteLength: positions.byteLength },
      { buffer: 0, byteOffset: positions.byteLength, byteLength: 6 },
    ],
    buffers: [{ byteLength: bin.length }],
  }, bin);
}

test('a GLB reads its chunks and its indexed geometry', () => {
  const m = parseGLB(triangleGLB());
  assert.equal(m.count, 3);
  assert.deepEqual([...m.positions], [0, 0, 0, 1, 0, 0, 0, 1, 0]);
});

test('a node transform is applied to the geometry under it', () => {
  const m = parseGLB(triangleGLB({ translation: [10, 0, 0], scale: [2, 2, 2] }));
  assert.deepEqual([...m.positions], [10, 0, 0, 12, 0, 0, 10, 2, 0]);
});

test('a node matrix and a TRS reach the same place', () => {
  const trs = parseGLB(triangleGLB({ translation: [1, 2, 3] }));
  const mat = parseGLB(triangleGLB({ matrix: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 2, 3, 1] }));
  assert.deepEqual([...trs.positions], [...mat.positions]);
});

test('a GLB with no geometry is an error', () => {
  const buf = glb({ asset: { version: '2.0' }, scenes: [{ nodes: [] }], scene: 0 }, new Uint8Array(0));
  assert.throws(() => parseGLB(buf), MeshError);
});

test('a truncated GLB is refused rather than read past its end', () => {
  const full = triangleGLB();
  assert.throws(() => parseGLB(full.slice(0, full.byteLength - 20)), MeshError);
});

test('a glTF pointing at an external buffer says so', () => {
  const doc = {
    asset: { version: '2.0' }, scene: 0, scenes: [{ nodes: [0] }],
    nodes: [{ mesh: 0 }],
    meshes: [{ primitives: [{ attributes: { POSITION: 0 } }] }],
    accessors: [{ bufferView: 0, componentType: 5126, count: 3, type: 'VEC3' }],
    bufferViews: [{ buffer: 0, byteOffset: 0, byteLength: 36 }],
    buffers: [{ uri: 'scene.bin', byteLength: 36 }],
  };
  const bytes = new TextEncoder().encode(JSON.stringify(doc)).buffer;
  assert.throws(() => parseGLB(bytes), /separate file/);
});

test('a node graph with a cycle in it terminates', () => {
  const doc = {
    asset: { version: '2.0' }, scene: 0, scenes: [{ nodes: [0] }],
    nodes: [{ children: [1] }, { children: [0] }],
  };
  const bytes = new TextEncoder().encode(JSON.stringify(doc)).buffer;
  // No geometry, so the error is the honest one - and crucially it arrives
  // rather than the walk running until the stack gives out.
  assert.throws(() => parseGLB(bytes), MeshError);
});

test('something that is not a glTF at all is refused', () => {
  assert.throws(() => parseGLB(new TextEncoder().encode('hello').buffer), MeshError);
});

// ---------------------------------------------------------------------------
// Routing
// ---------------------------------------------------------------------------

test('meshKind picks a parser from the extension', () => {
  assert.equal(meshKind('part.stl'), 'stl');
  assert.equal(meshKind('PART.STL'), 'stl');
  assert.equal(meshKind('scene.glb'), 'glb');
  assert.equal(meshKind('scene.gltf'), 'glb');
  assert.equal(meshKind('thing.obj'), 'obj');
  assert.equal(meshKind('photo.jpg'), null);
  assert.equal(meshKind('noextension'), null);
  assert.equal(meshKind(''), null);
});

test('parseMesh dispatches, and refuses a kind it does not have', () => {
  assert.equal(parseMesh('obj', new TextEncoder().encode('v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 3').buffer).count, 3);
  assert.throws(() => parseMesh('ply', new ArrayBuffer(8)), MeshError);
});

test('the triangle ceiling is a number a card could plausibly be asked for', () => {
  // Not a behaviour so much as a guard against someone "tidying" it to 100.
  assert.ok(MAX_TRIANGLES >= 1_000_000);
});
