// The three model parsers, against bytes rather than against a mock.
//
// Every fixture here is built in the test - a real binary STL laid out to the
// byte, a real GLB with its two chunks and its four-byte padding - because the
// whole point of writing these parsers by hand was to avoid a dependency, and
// checking them against a fixture generated by the same code would check
// nothing.

import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  parseSTL, parseOBJ, parseGLB, parseMesh, parseMTL, applyMaterials,
  defaultUpAxis, meshKind, MeshError, MAX_TRIANGLES, MAX_ELEMENTS,
} from '../web/assets/js/mesh.ts';

// A unit triangle in the z = 0 plane, wound anticlockwise so its normal is +z.
const TRI = {
  a: [0, 0, 0], b: [1, 0, 0], c: [0, 1, 0],
};

const near = (a, b, msg) => assert.ok(Math.abs(a - b) < 1e-5, `${msg}: ${a} vs ${b}`);

// ---------------------------------------------------------------------------
// STL
// ---------------------------------------------------------------------------

function binarySTL(triangles, header = 'a header') {
  const buf = new ArrayBuffer(84 + triangles.length * 50);
  const view = new DataView(buf);
  new Uint8Array(buf).set(new TextEncoder().encode(header.slice(0, 80)), 0);
  view.setUint32(80, triangles.length, true);
  triangles.forEach((t, i) => {
    const at = 84 + i * 50;
    const n = t.normal || [0, 0, 0];
    view.setFloat32(at, n[0], true);
    view.setFloat32(at + 4, n[1], true);
    view.setFloat32(at + 8, n[2], true);
    [t.a, t.b, t.c].forEach((v, k) => {
      view.setFloat32(at + 12 + k * 12, v[0], true);
      view.setFloat32(at + 16 + k * 12, v[1], true);
      view.setFloat32(at + 20 + k * 12, v[2], true);
    });
  });
  return buf;
}

test('a binary STL reads its triangles and its bounds', () => {
  const m = parseSTL(binarySTL([{ ...TRI, normal: [0, 0, 1] }]));
  assert.equal(m.count, 3);
  assert.deepEqual([...m.positions], [0, 0, 0, 1, 0, 0, 0, 1, 0]);
  assert.deepEqual(m.bounds.min, [0, 0, 0]);
  assert.deepEqual(m.bounds.max, [1, 1, 0]);
});

test('a binary STL whose header says "solid" is still binary', () => {
  // The bug this exists for: sniffing the leading word sends these files down
  // the ASCII path, where they parse as empty. The length arithmetic does not
  // care what the header says.
  const m = parseSTL(binarySTL([{ ...TRI, normal: [0, 0, 1] }], 'solid exported by something'));
  assert.equal(m.count, 3);
});

test('a facet with no normal gets the one its winding implies', () => {
  const m = parseSTL(binarySTL([{ ...TRI, normal: [0, 0, 0] }]));
  near(m.normals[0], 0, 'nx');
  near(m.normals[1], 0, 'ny');
  near(m.normals[2], 1, 'nz');
});

test('normals come out unit length whatever the file said', () => {
  const m = parseSTL(binarySTL([{ ...TRI, normal: [0, 0, 17] }]));
  near(Math.hypot(m.normals[0], m.normals[1], m.normals[2]), 1, 'length');
});

test('an ASCII STL reads the same triangle', () => {
  const text = `solid thing
  facet normal 0 0 1
    outer loop
      vertex 0 0 0
      vertex 1 0 0
      vertex 0 1 0
    endloop
  endfacet
endsolid thing`;
  const m = parseSTL(new TextEncoder().encode(text).buffer);
  assert.equal(m.count, 3);
  assert.deepEqual([...m.positions], [0, 0, 0, 1, 0, 0, 0, 1, 0]);
});

test('an ASCII STL survives exponents and negative numbers', () => {
  const text = `solid s
facet normal 0 0 1
outer loop
vertex -1.5e2 0 0
vertex 1 -2.25 0
vertex 0 1 3E-2
endloop
endfacet
endsolid s`;
  const m = parseSTL(new TextEncoder().encode(text).buffer);
  near(m.positions[0], -150, 'x');
  near(m.positions[4], -2.25, 'y');
  near(m.positions[8], 0.03, 'z');
});

test('an STL with nothing in it is an error, not an empty mesh', () => {
  assert.throws(() => parseSTL(new TextEncoder().encode('solid s\nendsolid s').buffer), MeshError);
});

test('a binary STL that lies about its triangle count is read as ASCII', () => {
  // 84 + 50n is the whole test for binary, so a header claiming a count the
  // length does not support must not be trusted to allocate against.
  const buf = new ArrayBuffer(200);
  new DataView(buf).setUint32(80, 4_000_000_000, true);
  assert.throws(() => parseSTL(buf), MeshError);
});

// ---------------------------------------------------------------------------
// OBJ
// ---------------------------------------------------------------------------

test('an OBJ reads faces and one-based indices', () => {
  const m = parseOBJ('v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 3\n');
  assert.equal(m.count, 3);
  assert.deepEqual([...m.positions], [0, 0, 0, 1, 0, 0, 0, 1, 0]);
});

test('an OBJ quad is fanned into two triangles', () => {
  const m = parseOBJ('v 0 0 0\nv 1 0 0\nv 1 1 0\nv 0 1 0\nf 1 2 3 4\n');
  assert.equal(m.count, 6);
});

test('negative OBJ indices count back from what has been read', () => {
  const m = parseOBJ('v 0 0 0\nv 1 0 0\nv 0 1 0\nf -3 -2 -1\n');
  assert.deepEqual([...m.positions], [0, 0, 0, 1, 0, 0, 0, 1, 0]);
});

test('an OBJ face may name normals, or leave them to be computed', () => {
  const given = parseOBJ('v 0 0 0\nv 1 0 0\nv 0 1 0\nvn 0 1 0\nf 1//1 2//1 3//1\n');
  near(given.normals[1], 1, 'the file said +y');
  const derived = parseOBJ('v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 3\n');
  near(derived.normals[2], 1, 'the winding says +z');
});

test('an OBJ ignores what it cannot draw rather than failing on it', () => {
  const m = parseOBJ([
    '# a comment', 'mtllib thing.mtl', 'o Object', 'g group', 's 1',
    'usemtl red', 'vt 0.5 0.5',
    'v 0 0 0', 'v 1 0 0', 'v 0 1 0', 'f 1/1 2/1 3/1', '',
  ].join('\n'));
  assert.equal(m.count, 3);
});

test('an OBJ with no faces is an error', () => {
  assert.throws(() => parseOBJ('v 0 0 0\nv 1 0 0\n'), MeshError);
});

// ---------------------------------------------------------------------------
// GLB
// ---------------------------------------------------------------------------

/** A real container: header, JSON chunk, BIN chunk, both padded to four. */
function glb(json, bin) {
  const enc = new TextEncoder();
  const pad = (bytes, filler) => {
    const need = (4 - (bytes.length % 4)) % 4;
    if (!need) return bytes;
    const out = new Uint8Array(bytes.length + need);
    out.set(bytes);
    out.fill(filler, bytes.length);
    return out;
  };
  const j = pad(enc.encode(JSON.stringify(json)), 0x20);   // spaces
  const b = pad(bin, 0);
  const total = 12 + 8 + j.length + 8 + b.length;
  const buf = new ArrayBuffer(total);
  const v = new DataView(buf);
  const u = new Uint8Array(buf);
  v.setUint32(0, 0x46546c67, true);
  v.setUint32(4, 2, true);
  v.setUint32(8, total, true);
  v.setUint32(12, j.length, true);
  v.setUint32(16, 0x4e4f534a, true);
  u.set(j, 20);
  const at = 20 + j.length;
  v.setUint32(at, b.length, true);
  v.setUint32(at + 4, 0x004e4942, true);
  u.set(b, at + 8);
  return buf;
}

/** One triangle: three VEC3 positions, then three unsigned-short indices. */
function triangleGLB(extra = {}) {
  const positions = new Float32Array([0, 0, 0, 1, 0, 0, 0, 1, 0]);
  const indices = new Uint16Array([0, 1, 2]);
  const bin = new Uint8Array(positions.byteLength + 8);   // 8 = indices, padded
  bin.set(new Uint8Array(positions.buffer), 0);
  bin.set(new Uint8Array(indices.buffer), positions.byteLength);
  return glb({
    asset: { version: '2.0' },
    scene: 0,
    scenes: [{ nodes: [0] }],
    nodes: [{ mesh: 0, ...extra }],
    meshes: [{ primitives: [{ attributes: { POSITION: 0 }, indices: 1 }] }],
    accessors: [
      { bufferView: 0, componentType: 5126, count: 3, type: 'VEC3' },
      { bufferView: 1, componentType: 5123, count: 3, type: 'SCALAR' },
    ],
    bufferViews: [
      { buffer: 0, byteOffset: 0, byteLength: positions.byteLength },
      { buffer: 0, byteOffset: positions.byteLength, byteLength: 6 },
    ],
    buffers: [{ byteLength: bin.length }],
  }, bin);
}

test('a GLB reads its chunks and its indexed geometry', () => {
  const m = parseGLB(triangleGLB());
  assert.equal(m.count, 3);
  assert.deepEqual([...m.positions], [0, 0, 0, 1, 0, 0, 0, 1, 0]);
});

test('a node transform is applied to the geometry under it', () => {
  const m = parseGLB(triangleGLB({ translation: [10, 0, 0], scale: [2, 2, 2] }));
  assert.deepEqual([...m.positions], [10, 0, 0, 12, 0, 0, 10, 2, 0]);
});

test('a node matrix and a TRS reach the same place', () => {
  const trs = parseGLB(triangleGLB({ translation: [1, 2, 3] }));
  const mat = parseGLB(triangleGLB({ matrix: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 2, 3, 1] }));
  assert.deepEqual([...trs.positions], [...mat.positions]);
});

test('a GLB with no geometry is an error', () => {
  const buf = glb({ asset: { version: '2.0' }, scenes: [{ nodes: [] }], scene: 0 }, new Uint8Array(0));
  assert.throws(() => parseGLB(buf), MeshError);
});

test('a truncated GLB is refused rather than read past its end', () => {
  const full = triangleGLB();
  assert.throws(() => parseGLB(full.slice(0, full.byteLength - 20)), MeshError);
});

test('a glTF pointing at an external buffer says so', () => {
  const doc = {
    asset: { version: '2.0' }, scene: 0, scenes: [{ nodes: [0] }],
    nodes: [{ mesh: 0 }],
    meshes: [{ primitives: [{ attributes: { POSITION: 0 } }] }],
    accessors: [{ bufferView: 0, componentType: 5126, count: 3, type: 'VEC3' }],
    bufferViews: [{ buffer: 0, byteOffset: 0, byteLength: 36 }],
    buffers: [{ uri: 'scene.bin', byteLength: 36 }],
  };
  const bytes = new TextEncoder().encode(JSON.stringify(doc)).buffer;
  assert.throws(() => parseGLB(bytes), /separate file/);
});

test('a node graph with a cycle in it terminates', () => {
  const doc = {
    asset: { version: '2.0' }, scene: 0, scenes: [{ nodes: [0] }],
    nodes: [{ children: [1] }, { children: [0] }],
  };
  const bytes = new TextEncoder().encode(JSON.stringify(doc)).buffer;
  // No geometry, so the error is the honest one - and crucially it arrives
  // rather than the walk running until the stack gives out.
  assert.throws(() => parseGLB(bytes), MeshError);
});

test('something that is not a glTF at all is refused', () => {
  assert.throws(() => parseGLB(new TextEncoder().encode('hello').buffer), MeshError);
});

// ---------------------------------------------------------------------------
// Routing
// ---------------------------------------------------------------------------

test('meshKind picks a parser from the extension', () => {
  assert.equal(meshKind('part.stl'), 'stl');
  assert.equal(meshKind('PART.STL'), 'stl');
  assert.equal(meshKind('scene.glb'), 'glb');
  assert.equal(meshKind('scene.gltf'), 'glb');
  assert.equal(meshKind('thing.obj'), 'obj');
  assert.equal(meshKind('photo.jpg'), null);
  assert.equal(meshKind('noextension'), null);
  assert.equal(meshKind(''), null);
});

test('parseMesh dispatches, and refuses a kind it does not have', () => {
  assert.equal(parseMesh('obj', new TextEncoder().encode('v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 3').buffer).count, 3);
  assert.throws(() => parseMesh('ply', new ArrayBuffer(8)), MeshError);
});

// ---------------------------------------------------------------------------
// Which way is up
// ---------------------------------------------------------------------------
//
// STL is Z-up and the viewer is Y-up, so parseMesh() stands STL geometry up on
// the way through and leaves the other two alone. This is the difference
// between a part on its feet and a part on its back, and nothing else in the
// app can tell - the renderer is handed points and draws them.

test('parseMesh stands a Z-up STL upright, points and box together', () => {
  // A triangle standing up the Z axis, which is what "up" means in an STL.
  const tall = { a: [0, 0, 0], b: [1, 0, 0], c: [0, 0, 4], normal: [0, -1, 0] };
  const m = parseMesh('stl', binarySTL([tall]));

  // Negating a coordinate of zero gives -0, which is the same number and a
  // different value to deepEqual. Flattened rather than worked around, because
  // "the sign of nothing" is not a property this should be asserting.
  const flat = a => [...a].map(n => (n === 0 ? 0 : n));

  // (x, y, z) -> (x, z, -y): the height moves out of Z and into Y.
  assert.deepEqual(flat(m.positions), [0, 0, 0, 1, 0, 0, 0, 4, 0]);
  assert.deepEqual(flat(m.normals).slice(0, 3), [0, 0, 1]);

  // The box has to travel with the points. The renderer frames the model from
  // bounds alone, so a mesh whose geometry stood up and whose box did not would
  // look right and be framed from the wrong place - centred on nothing, and
  // clipped or tiny depending on the part.
  assert.deepEqual(flat(m.bounds.min), [0, 0, 0]);
  assert.deepEqual(flat(m.bounds.max), [1, 4, 0]);

  // And the box must still be the box: every point inside it, on every axis.
  for (let i = 0; i < m.positions.length; i += 3) {
    for (const k of [0, 1, 2]) {
      assert.ok(m.positions[i + k] >= m.bounds.min[k] - 1e-6
             && m.positions[i + k] <= m.bounds.max[k] + 1e-6,
        `point ${i / 3} is outside the bounds on axis ${k}`);
    }
  }
});

test('the rotation is a rotation: nothing is stretched or mirrored', () => {
  const tri = { a: [1, 2, 3], b: [-4, 0.5, 2], c: [0, -3, 7], normal: [0, 1, 0] };
  const raw = parseSTL(binarySTL([tri]));
  const up = parseMesh('stl', binarySTL([tri]));
  const edge = (p, i, j) => Math.hypot(
    p[i * 3] - p[j * 3], p[i * 3 + 1] - p[j * 3 + 1], p[i * 3 + 2] - p[j * 3 + 2]);
  for (const [i, j] of [[0, 1], [1, 2], [2, 0]]) {
    near(edge(raw.positions, i, j), edge(up.positions, i, j), `edge ${i}-${j} changed length`);
  }
  // Normals stay unit length - they are rotated, not transformed by something
  // with a scale hidden in it.
  near(Math.hypot(up.normals[0], up.normals[1], up.normals[2]), 1, 'normal length');
});

test('OBJ defaults to Z-up, and the default can be overridden', () => {
  // OBJ's up-axis is the one guess in this file: the format says nothing, CAD
  // and scanning tools write Z-up, Blender's exporter writes Y-up. Z-up is the
  // default because it is the company OBJ keeps beside STL, and because being
  // wrong is recoverable - `meta.upAxis` reaches this argument.
  const src = new TextEncoder().encode('v 0 0 0\nv 1 0 0\nv 0 0 5\nf 1 2 3').buffer;
  const flat = a => [...a].map(n => (n === 0 ? 0 : n));

  const guessed = parseMesh('obj', src);
  assert.deepEqual(flat(guessed.positions), [0, 0, 0, 1, 0, 0, 0, 5, 0]);
  assert.deepEqual(flat(guessed.bounds.max), [1, 5, 0]);

  const asWritten = parseMesh('obj', src, 'y');
  assert.deepEqual(flat(asWritten.positions), [0, 0, 0, 1, 0, 0, 0, 0, 5]);
  assert.deepEqual(flat(asWritten.bounds.max), [1, 0, 5]);

  // And an STL can be told it was Y-up all along, for the exporter that wrote
  // one from a Y-up scene.
  const stl = parseMesh('stl', binarySTL([{ a: [0, 0, 0], b: [1, 0, 0], c: [0, 0, 5] }]), 'y');
  assert.deepEqual(flat(stl.positions), [0, 0, 0, 1, 0, 0, 0, 0, 5]);

  // A value that is neither falls back to the format's default rather than
  // doing something arbitrary - it arrives from meta in somebody's .mbrd.
  for (const junk of [null, undefined, '', 'up', 42]) {
    assert.deepEqual(flat(parseMesh('obj', src, junk).positions),
      flat(guessed.positions), `upAxis ${JSON.stringify(junk)} was not ignored`);
  }
});

test('glTF is left exactly as it was, because its spec settles the question', () => {
  assert.equal(defaultUpAxis('glb'), 'y');
  assert.equal(defaultUpAxis('obj'), 'z');
  assert.equal(defaultUpAxis('stl'), 'z');
});

// ---------------------------------------------------------------------------
// OBJ colour
// ---------------------------------------------------------------------------
//
// Two independent sources, and a model may use either, both or neither. The
// buffer they produce has to line up 1:1 with the positions - three floats per
// triangle vertex, in the order the faces were emitted - because the renderer
// draws the whole mesh in one call with no index of its own, so a colour array
// that is merely the right *length* but the wrong order is a bug that renders
// as plausible nonsense.

const obj = s => parseOBJ(new TextEncoder().encode(s).buffer);

test('embedded per-vertex colours are read off the v lines', () => {
  // The unofficial `v x y z r g b`, which is what scanners and photogrammetry
  // tools write. Three vertices, three colours, one triangle.
  const m = obj([
    'v 0 0 0 1 0 0',
    'v 1 0 0 0 1 0',
    'v 0 1 0 0 0 1',
    'f 1 2 3',
  ].join('\n'));
  assert.equal(m.colors.length, m.positions.length);
  assert.deepEqual([...m.colors], [1, 0, 0, 0, 1, 0, 0, 0, 1]);
});

test('a vertex without a colour is white, so the array stays parallel', () => {
  // Mixed is the case that breaks a parser that only pushes when it sees six
  // numbers: the colours then slide out of step with the vertices and every
  // face after the first is painted with somebody else's colour.
  const m = obj(['v 0 0 0', 'v 1 0 0 0 1 0', 'v 0 1 0', 'f 1 2 3'].join('\n'));
  assert.deepEqual([...m.colors], [1, 1, 1, 0, 1, 0, 1, 1, 1]);
});

test('a plain OBJ has no colours at all', () => {
  // Null rather than an array of white: it is what the renderer switches on, and
  // a model that said nothing about colour has to come out in the board's ink.
  const m = obj(['v 0 0 0', 'v 1 0 0', 'v 0 1 0', 'f 1 2 3'].join('\n'));
  assert.equal(m.colors, null);
  assert.equal(m.mtllib, null);
  assert.equal(m.triMat, null);
});

test('colours follow a fan triangulation', () => {
  // A quad becomes two triangles sharing vertex 1, so vertex 1's colour has to
  // appear in both. This is the assertion that catches a colour buffer built
  // per-vertex instead of per-triangle-corner.
  const m = obj([
    'v 0 0 0 1 0 0',
    'v 1 0 0 0 1 0',
    'v 1 1 0 0 0 1',
    'v 0 1 0 1 1 0',
    'f 1 2 3 4',
  ].join('\n'));
  assert.equal(m.count, 6);
  assert.deepEqual([...m.colors].slice(0, 3), [1, 0, 0]);
  assert.deepEqual([...m.colors].slice(9, 12), [1, 0, 0]);
  assert.deepEqual([...m.colors].slice(15, 18), [1, 1, 0]);
});

test('usemtl and mtllib are carried out for the caller to resolve', () => {
  const m = obj([
    'mtllib parts.mtl',
    'v 0 0 0', 'v 1 0 0', 'v 0 1 0', 'v 0 0 1',
    'usemtl red',
    'f 1 2 3',
    'usemtl blue',
    'f 1 2 4',
  ].join('\n'));
  assert.equal(m.mtllib, 'parts.mtl');
  assert.deepEqual(m.triMat, ['red', 'blue']);
  assert.equal(m.colors, null, 'a material name is not a colour on its own');
});

test('a .mtl yields its diffuse colours and skips what is not one', () => {
  const mats = parseMTL([
    'newmtl red',
    'Ka 0.1 0.1 0.1',
    'Kd 1 0 0',
    'newmtl blue',
    'Kd 0 0 1',
    'newmtl textured',
    'map_Kd wood.png',
    'newmtl spectral',
    'Kd spectral file.rfl 1.0',
  ].join('\n'));
  assert.deepEqual(mats.get('red'), [1, 0, 0]);
  assert.deepEqual(mats.get('blue'), [0, 0, 1]);
  // Present but colourless, which is different from absent - the mesh falls
  // back to the board's ink for these rather than to black.
  assert.equal(mats.get('textured'), null);
  // `Kd spectral <file>` is legal and is not three floats. Parsed as one it
  // would be NaN, which draws as black.
  assert.equal(mats.get('spectral'), null);
});

test('materials bake into the mesh, one colour per triangle', () => {
  const m = obj([
    'mtllib p.mtl',
    'v 0 0 0', 'v 1 0 0', 'v 0 1 0', 'v 0 0 1',
    'usemtl red', 'f 1 2 3',
    'usemtl blue', 'f 1 2 4',
  ].join('\n'));
  assert.ok(applyMaterials(m, parseMTL('newmtl red\nKd 1 0 0\nnewmtl blue\nKd 0 0 1')));
  assert.equal(m.colors.length, m.positions.length);
  // All three corners of triangle one are red, all three of triangle two blue.
  assert.deepEqual([...m.colors].slice(0, 9), [1, 0, 0, 1, 0, 0, 1, 0, 0]);
  assert.deepEqual([...m.colors].slice(9, 18), [0, 0, 1, 0, 0, 1, 0, 0, 1]);
});

test('a triangle whose material resolved to nothing stays white, not black', () => {
  // Zero is the Float32Array's default and it is the one value that must not
  // survive: an unmatched material would render as a black facet in the middle
  // of a coloured part, which reads as a hole.
  const m = obj([
    'v 0 0 0', 'v 1 0 0', 'v 0 1 0', 'v 0 0 1',
    'usemtl red', 'f 1 2 3',
    'usemtl missing', 'f 1 2 4',
  ].join('\n'));
  assert.ok(applyMaterials(m, parseMTL('newmtl red\nKd 1 0 0')));
  assert.deepEqual([...m.colors].slice(9, 18), [1, 1, 1, 1, 1, 1, 1, 1, 1]);
});

test('a library that colours nothing leaves the mesh alone', () => {
  // False, and no colours attached - so the card falls back to the palette
  // rather than to the grey a "default material" would give it.
  const m = obj(['v 0 0 0', 'v 1 0 0', 'v 0 1 0', 'usemtl red', 'f 1 2 3'].join('\n'));
  assert.equal(applyMaterials(m, parseMTL('newmtl other\nKd 1 0 0')), false);
  assert.equal(m.colors, null);
  assert.equal(applyMaterials(m, new Map()), false);
});

test('embedded colours win over a material library', () => {
  // The file's own per-vertex answer is more specific than a name pointing at a
  // second file, and parseOBJ attaches it - so applyMaterials is never reached
  // for these. Asserted because the precedence is a decision, not an accident.
  const m = obj([
    'mtllib p.mtl',
    'v 0 0 0 1 0 0', 'v 1 0 0 1 0 0', 'v 0 1 0 1 0 0',
    'usemtl blue', 'f 1 2 3',
  ].join('\n'));
  assert.deepEqual([...m.colors].slice(0, 3), [1, 0, 0]);
});

test('colours outside 0-1 are clamped rather than passed to the shader', () => {
  // 0-255 colours turn up in the wild, and a value of 255 in a float attribute
  // is a facet that blows out to white and takes its neighbours' shading with
  // it. Clamped, not rescaled: guessing the scale from the values would make
  // a legitimately bright model dark.
  const m = obj(['v 0 0 0 255 -3 0.5', 'v 1 0 0', 'v 0 1 0', 'f 1 2 3'].join('\n'));
  assert.deepEqual([...m.colors].slice(0, 3), [1, 0, 0.5]);
});

test('the triangle ceiling is a number a card could plausibly be asked for', () => {
  // Not a behaviour so much as a guard against someone "tidying" it to 100.
  // Both ends: a ceiling raised out of the way is the same as no ceiling, and
  // this file's whole other half is about what an unbounded count costs.
  assert.ok(MAX_TRIANGLES >= 1_000_000, `MAX_TRIANGLES is ${MAX_TRIANGLES} - too low for a real model`);
  assert.ok(MAX_TRIANGLES <= 20_000_000, `MAX_TRIANGLES is ${MAX_TRIANGLES} - that is not a ceiling`);
});

// ---------------------------------------------------------------------------
// glTF hostile-input guards (AUD-06)
//
// parseGLB accepts a bare glTF JSON document as well as a GLB container, so a
// fixture is just an object encoded to bytes - no binary chunk to assemble.
// ---------------------------------------------------------------------------

const gltfBytes = doc => new TextEncoder().encode(JSON.stringify(doc)).buffer;

test('a small embedded glTF still parses through the new guards', () => {
  const pos = new Float32Array([0, 0, 0, 1, 0, 0, 0, 1, 0]);
  const b64 = Buffer.from(pos.buffer).toString('base64');
  const mesh = parseGLB(gltfBytes({
    accessors: [{ type: 'VEC3', componentType: 5126, count: 3, bufferView: 0 }],
    bufferViews: [{ buffer: 0, byteOffset: 0, byteLength: 36 }],
    buffers: [{ byteLength: 36, uri: 'data:application/octet-stream;base64,' + b64 }],
    meshes: [{ primitives: [{ attributes: { POSITION: 0 } }] }],
    nodes: [{ mesh: 0 }],
    scenes: [{ nodes: [0] }],
  }));
  assert.equal(mesh.positions.length, 9);
});

test('an accessor that declares an implausible count is refused before it allocates', () => {
  assert.throws(() => parseGLB(gltfBytes({
    accessors: [{ type: 'VEC3', componentType: 5126, count: MAX_ELEMENTS + 1, bufferView: 0 }],
    bufferViews: [{ buffer: 0, byteLength: 12 }],
    buffers: [{ byteLength: 12 }],
    meshes: [{ primitives: [{ attributes: { POSITION: 0 } }] }],
    nodes: [{ mesh: 0 }],
    scenes: [{ nodes: [0] }],
  })), /implausible amount of geometry/);
});

test('a non-integer accessor count is refused rather than truncated', () => {
  assert.throws(() => parseGLB(gltfBytes({
    accessors: [{ type: 'VEC3', componentType: 5126, count: 1.5, bufferView: 0 }],
    bufferViews: [{ buffer: 0, byteLength: 36 }],
    buffers: [{ byteLength: 36 }],
    meshes: [{ primitives: [{ attributes: { POSITION: 0 } }] }],
    nodes: [{ mesh: 0 }],
    scenes: [{ nodes: [0] }],
  })), /implausible amount of geometry/);
});

test('a deep acyclic node chain is refused instead of overflowing the stack', () => {
  const N = 5000;   // past MAX_NODE_DEPTH; a recursion would have blown up here
  const nodes = Array.from({ length: N }, (_, i) => (i < N - 1 ? { children: [i + 1] } : {}));
  assert.throws(() => parseGLB(gltfBytes({ nodes, scenes: [{ nodes: [0] }] })),
    /nested too deeply/);
});
