// The app is its own 404 page, and the deploy is the half of that design no
// test could see until now.
//
// Locally serve.py decouples body from status: a miss gets index.html read off
// disk and a 404 in the status line, so there is nothing to keep in sync. A
// static host cannot do that. Cloudflare Workers answers a miss with whatever
// file is called 404.html, at whatever status that file implies, and the only
// way to say "the app, with a 404" is to put a second copy of the app there.
//
// So web/404.html exists and is index.html byte for byte. Nothing at runtime
// notices when it stops being: the copy is the page nobody opens, and the way
// it fails is that visitors arriving at a dead link get a build of the app from
// whenever the two last agreed - the right shell name, older markup, and a
// service worker that hands them a version of the document its cache has never
// heard of. save.bat remakes the copy on every commit; this is the check that
// the remake happened, and the reason a hand-edited 404.html is a mistake.
//
// The second test guards the setting that makes the file mean anything. Workers
// serves 404.html only when told to - the default is a bare edge 404 the app
// never sees, and the other option serves the shell with a 200, which is a soft
// 404: a page saying "not found" while telling every crawler it is fine. That
// used to be a `404` status line in web/_redirects, which Workers rejects
// outright (the deploy fails, it does not degrade), which is why the rule moved
// here.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { join } from 'node:path';
import { readFileSync } from 'node:fs';

import { ROOT, WEB } from './helpers.js';

test('web/404.html is index.html, byte for byte', () => {
  // Read as bytes, not text: a copy that differs only in its BOM or its line
  // endings is still a copy that was made by hand, and the next thing to go
  // that way is the markup.
  const index = readFileSync(join(WEB, 'index.html'));
  const notfound = readFileSync(join(WEB, '404.html'));

  assert.ok(notfound.equals(index),
    'web/404.html has drifted from web/index.html - it is a generated byte copy, remade by save.bat; do not hand-edit it');
});

test('the deploy config serves 404.html at a 404, not a bare miss or a soft one', () => {
  // Read as text and matched loosely. wrangler.jsonc is JSONC - comments, and
  // this file carries a lot of them - so this is a check that the setting is
  // present and says the right thing, not a parse.
  const cfg = readFileSync(join(ROOT, 'wrangler.jsonc'), 'utf8');

  assert.match(cfg, /"not_found_handling"\s*:\s*"404-page"/,
    'wrangler.jsonc must set assets.not_found_handling to "404-page" - without it a miss never reaches the app');
  assert.match(cfg, /"directory"\s*:\s*"\.\/web"/,
    'wrangler.jsonc must serve web/ - the 404 page is only found beside the rest of the app');
});
